- name: Install Docker & Compose
  pacman:
    name:
      - docker
      - docker-compose
    state: present
- name: Enable and start Docker
  systemd:
    name: docker
    state: started
    enabled: yes
- name: Install docker-compose files
  template:
    dest: /var/cache/garuda-{{ inventory_hostname | lower }}/docker-compose.yml
    group: root
    mode: 0644
    owner: root
    src: "{{ inventory_hostname }}/docker-compose.yml.j2"
- name: Copy static configurations to target directory
  copy:
    src: "{{ inventory_hostname }}/"
    dest: /var/cache/garuda-{{ inventory_hostname }}
    follow: yes
- name: Run docker-compose up -d
  shell: docker-compose up -d --remove-orphans
  args:
    chdir: /var/cache/garuda-{{ inventory_hostname | lower }}
