# Base values
actual_hostname: garuda-iso
ansible_host: 78.129.140.86
crowdsec: true
letsencrypt_domain: "iso.builds.garudalinux.org"

# Devsec - we don't want to disable efi as its needed for iso builds
os_modprobe_enabled: false

# Zerotier
zerotier_member_description: garuda-iso
zerotier_member_ip_assignments: ["10.241.0.8"]
