- name: Install Borg
  pacman:
    name: borg
    state: present
- name: Create borg group
  group:
    name: borg
    state: present
- name: Ensure the repository directory exists
  user:
    createhome: yes
    group: borg
    home: "{{ borg_repo_dir }}"
    name: borg
    shell: /bin/bash
- name: Set permissions on the repository directory
  file:
    group: borg
    mode: 0700
    owner: borg
    path: "{{ borg_repo_dir }}"
    state: directory
- name: Create .ssh directory for the borg user
  file:
    group: borg
    mode: 0700
    owner: borg
    path: "{{ borg_repo_dir }}/.ssh"
    state: directory
- name: Create the backup directory with correct permissions
  file:
    path: "{{ borg_repo_dir }}/{{ item }}"
    state: directory
    mode: 0700
    owner: borg
    group: borg
  with_items: "{{ borg_clients }}"
- name: Set permissions for the .ssh files
  file:
    group: borg
    mode: 0600
    owner: borg
    path: "{{ borg_repo_dir }}/.ssh/authorized_keys"
    state: file
- name: Create backup directories
  file:
    group: borg
    mode: 0700
    owner: borg
    path: "{{ borg_repo_dir }}/{{ item }}"
    state: directory
  with_items: "{{ borg_clients }}"
- name: Fetch ssh keys from each Borg client machine
  command: cat /root/.ssh/id_rsa.pub
  register: ssh_keys
  delegate_to: "{{ item }}"
  with_items: "{{ borg_clients }}"
  changed_when: ssh_keys.stdout | length > 0
- name: Allow certain clients to connect
  authorized_key:
    key: "{{ item.stdout }}"
    key_options: 'command="borg serve --restrict-to-path {{ borg_repo_dir }}/{{ item[''item''] }}",restrict'
    manage_dir: true
    user: borg
  with_items: "{{ ssh_keys.results }}"
- name: Install compact_repo script
  copy:
    dest: /usr/local/bin/compact_repo.sh
    group: root
    mode: 0644
    owner: root
    src: compact_repo.sh
- name: Make compact_repo script executable
  file:
    dest: /usr/local/bin/compact_repo.sh
    mode: a+x
- name: Install systemd units for compact repo task
  copy:
    dest: /etc/systemd/system/{{ item }}
    group: root
    mode: 0644
    owner: root
    src: "{{ item }}"
  loop:
    - compact_repo.service
    - compact_repo.timer
  notify: systemd daemon-reload
- name: Enable compact_repo.timer
  systemd:
    enabled: yes
    name: compact_repo.timer
    state: started
