tunnel: 81461915-3a1f-40e8-b348-fdb4b5aa5eb1
credentials-file: /root/.cloudflared/tunnel.json

ingress:
  - hostname: mesh.garudalinux.net
    service: http://app:443
    originRequest:
      noTLSVerify: true
  - hostname: npm.garudalinux.net
    service: http://app:81
  - hostname: matrixadmin.garudalinux.net
    service: http://matrix_admin:80
  - service: http_status:404
