# Base values
actual_hostname: garuda-web
ansible_host: 216.158.66.107
borg_dir: /var/cache/garuda-web
docker_compose: true

# Zerotier
zerotier_member_description: garuda-web
zerotier_member_ip_assignments: ["10.241.0.4"]
