version: "3.7"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    hostname: ${DOMAIN_NAME:?err}
    volumes:
      - "/srv/http/repos/:/var/lib/nginx/html/repo/:ro"
      - "./letsencrypt/etc:/etc/letsencrypt:ro"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/conf.d:/etc/nginx/conf.d:ro"
    ports:
      - "80:80"
      - "443:443"
    labels:
      com.datadoghq.ad.check_names: '["nginx"]'
      com.datadoghq.ad.init_configs: "[{}]"
      com.datadoghq.ad.instances: '[{"nginx_status_url": "http://%%host%%:81/nginx_status/"}]'

  syncthing:
    image: linuxserver/syncthing:latest
    container_name: syncthing
    hostname: ${DOMAIN_NAME:?err}
    env_file:
      - .env
    volumes:
      - "./syncthing:/config"
      - "/srv/http/repos/:/repo"
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
