---
- import_playbook: garuda.yml
- import_playbook: server_config.yml
- import_playbook: hardening.yml
- import_playbook: borg_clients.yml
- import_playbook: mirrors.yml
- import_playbook: chaotic_aur.yml
