---
- hosts: garuda
  gather_facts: yes
  become: true
  tasks:
    - import_role:
        name: common
    - import_role:
        name: zerotier
      when: zerotier_member_ip_assignments is defined
    - import_role:
        name: nico
