---
- name: Update garudalinux.org
  git:
    repo: https://gitlab.com/garuda-linux/website/garuda/
    depth: 1
    single_branch: true
    dest: /var/cache/garuda-{{ inventory_hostname | lower }}/website
    force: yes
  when: '"esxi-web" == inventory_hostname'
- name: Update the Chaotic-AUR toolbox on builders
  git:
    depth: 1
    dest: /var/cache/garuda-{{ inventory_hostname | lower }}/toolbox
    force: yes
    repo: https://github.com/chaotic-aur/toolbox.git
    single_branch: yes
  when: '"build" in inventory_hostname or "chaotic_builder" in inventory_hostname or "repo" in inventory_hostname'
- name: Install changed toolbox files
  shell: make install
  args:
    chdir: /var/cache/garuda-{{ inventory_hostname | lower }}/toolbox
  when: '"build" in inventory_hostname or "repo" in inventory_hostname'
